@base_url = http://localhost:5277/api

# FUNCIONÁRIO ######################################

### Criação de um novo funcionário
POST {{base_url}}/funcionario/cadastrar
Content-Type: application/json

{
    "nome": "Diogo",
    "cpf" : "12345678912"
}

### Obtenção de todos os funcionários
GET {{base_url}}/funcionario/listar

# FOLHA ############################################

### Criação de uma nova folha
POST {{base_url}}/folha/cadastrar
Content-Type: application/json

{
    "valor": 30,
    "quantidade" : 100,
    "mes" : 11,
    "ano" : 2023,
    "funcionarioId" : 1
}

### Obtenção de todas as folhas
GET {{base_url}}/folha/listar

### Obtenção de uma folha
GET {{base_url}}/folha/buscar/12345678912/11/2023