### Requisação para a raiz da aplicação
GET http://localhost:5020

### Listar produtos
GET http://localhost:5020/api/produto/listar

### Buscar produto
GET http://localhost:5020/api/produto/buscar/e05cc469-d0df-462e-82ae-5153aaf3f540

### Cadastrar produto
POST http://localhost:5020/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Água",
    "preco" : 4.5,
    "quantidade" : 153,
    "descricao" : "Alimento"
}

### Deletar produto
DELETE http://localhost:5020/api/produto/deletar/eef38bd9-3752-4f7e-b0fd-5bb95c88da05

### Alterar produto
PUT http://localhost:5020/api/produto/alterar/32b786e5-484a-4a20-93cf-6bf928175e7d
Content-Type: application/json

{
    "nome" : "Água",
    "preco" : 4.5,
    "quantidade" : 153
}

